src/go.mod
src/registry/registry.go
src/registry/registry_windows.go
src/shell/env.go
src/shell/path.go
website/docs/setup/env.mdx
website/docs/setup/path.mdx

feat(windows): persist to registry on demand

---

.github/workflows/bluesky.yml
.github/workflows/contributors.yml

feature driven

---

.github/workflows/edit_rights.yml
src/shell/aliae_test.go
src/shell/pwsh.go

fix(pwsh): only export alias with $args

---

.github/workflows/discord.yml

- fix(pwsh): only export alias with $args
- chore: expose token in workflow
- chore(discord): add webhook

fix discord (maybe)

---

src/context/runtime.go
website/docs/setup/templates.mdx

feat: add .Arch template variable

---

src/.goreleaser.yml

Adds schema to GoReleaser configuration. Will help in autocomplete suggestions, given by VSCode's IntelliSense.

chore: add schema to goreleaser config

---

.commitlintrc.yml
src/config/config.go

fix(config): load ALIAE_CONFIG first

---

.github/workflows/release.yml

Use new parameters instead of old & deprecated ones.

ci(release): update args for goreleaser

---

src/shell/git.go
src/shell/git_test.go

fix(git): do not evaluate expressions

---

.github/workflows/code.yml
.github/workflows/codeql.yml
.github/workflows/gomod.yml
.github/workflows/release.yml
src/cli/root.go
src/cli/version.go
src/go.mod

- feat: upgrade to go1.22
- chore: ignore unused variables

upgrade go

---

src/config/unmarshal.go

There is a transient failure in the func map since it parses for "!include_dir" and "!include" -- Maps are unordered by nature in Go which means that when "!include" gets parsed first on a "!include_dir" directive it fails
Create a struct for the FuncMap which will order the `range` inherently
```bash
#!/usr/bin/env bash
good_count=0
bad_count=0
for i in {1..100}; do
if go test > /dev/null 2>&1; then
good_count=$((good_count+1))
else
bad_count=$((bad_count+1))
fi
done
echo "good_count: $good_count"
echo "bad_count: $bad_count"
```
```bash
❯ ./src/config/test.sh
good_count: 91
bad_count: 9
❯ ./test.sh
good_count: 83
bad_count: 17
```
```bash
❯ ./src/config/test.sh
good_count: 100
bad_count: 0
❯ ./test.sh
good_count: 100
bad_count: 0
```
```
❯ go test
PASS
ok …
```

fix: func map unordered inconsistency

---

src/.golangci.yml
src/cli/get.go
src/cli/init.go
src/cli/root.go
src/cli/version.go

chore(lint): remove init check

---

.github/workflows/code.yml
.github/workflows/codeql.yml
.github/workflows/gomod.yml
.github/workflows/release.yml
src/cli/init.go
src/core/init.go
src/shell/aliae.go
src/shell/echo.go
src/shell/env.go
src/shell/path.go
src/shell/pwsh.go
website/docusaurus.config.js
website/package.json

Windows compatibility

---

src/shell/env_test.go
src/shell/fish.go

fix(fish): export variables

---

src/shell/link_test.go
src/shell/pwsh.go

fix(pwsh): silence link output

---

src/cli/init.go
src/config/config_test.go
src/config/init.go
src/config/test/aliae.valid_generic.yaml
src/config/unmarshal.go
website/docs/setup/include.mdx

- **chore: move core to config**
- **feat(config): allow inline include**

inline includes

---

src/shell/link.go
src/shell/link_test.go
website/docs/setup/link.mdx

feat(link): create parent folder with mkdir: true

---

src/config/unmarshal_strings.go
src/config/unmarshal_strings_test.go

fix(yaml): only trim the first >

---

website/docs/setup/configuration.mdx
website/static/schema.json

docs: add schema.json

---

src/config/config.go

fix(config): replace ~ with HOME dir
